In [2]:
import pandas as pd
import yfinance as yf

bbca = yf.download('BBCA.JK', start = "2020-01-01")

bbca.head()

C:\Users\rhama\AppData\Local\Temp\ipykernel_33344\3995966341.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  bbca = yf.download('BBCA.JK', start = "2020-01-01")
[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open    Volume
Ticker          BBCA.JK      BBCA.JK      BBCA.JK      BBCA.JK   BBCA.JK
Date
2020-01-02  5820.927246  5899.235684  5812.226309  5825.277715  49445000
2020-01-03  5916.637695  5916.637695  5851.380662  5873.133006  47755500
2020-01-06  5860.081055  5873.132460  5820.926838  5847.029649  27300000
2020-01-07  5864.430664  5890.533471  5855.729728  5860.080196  45022500
2020-01-08  5812.226074  5868.782166  5803.525137  5803.525137  53692500

In [3]:
bbca.describe()

Price          Close          High           Low          Open        Volume
Ticker       BBCA.JK       BBCA.JK       BBCA.JK       BBCA.JK       BBCA.JK
count    1350.000000   1350.000000   1350.000000   1350.000000  1.350000e+03
mean     7451.933567   7522.937073   7384.876993   7454.673882  9.070147e+07
std      1587.066698   1589.440444   1583.643026   1584.601392  6.017384e+07
min      3854.515137   4248.649659   3763.155594   3871.916463  0.000000e+00
25%      5920.346191   5941.727539   5865.204440   5916.637908  5.777782e+07
50%      7649.934082   7726.787387   7569.551304   7635.074847  7.755440e+07
75%      8663.289062   8733.722097   8598.214092   8682.385367  1.055364e+08
max     10570.414062  10570.414062  10401.480469  10522.147296  7.564316e+08